export const config = {
    host: 'localhost',
    port: 8081,
    swagger: {
        swaggerDefinition: {
            // Like the one described here: https://swagger.io/specification/#infoObject
            info: {
                title: 'Meme-ory',
                version: '1.0.0',
                description: 'Test Express API with autogenerated swagger doc',
            },
        },
        // List of files to be processes. You can also set globs './routes/*.js'
        apis: ['server.js'],
    }
};

